config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  scope '/checkout' do
    post 'create' , to: 'checkout#create' , as: 'checkout_create'
    get 'cancel' , to: 'checkout#cancel' , as: 'checkout_cancel'
    get 'success' , to: 'checkout#success' , as: 'checkout_success'
  end

  get 'freecases' , to: 'cases#freeindex' , as: 'free_cases'
  get 'profile' , to: 'cases#profile', as: 'profile'
  post 'freecases/protect' , to: 'cases#freeprotect' , as: 'protect_case'
  post 'cases/cancel' , :to => 'cases#remove' , as:'donor_cancel'
  post 'cases/protect' , :to => 'cases#protect' , as: 'donor_protect'
  put 'cases/updatestate/:id', to: 'cases#updatestate'
  get 'search/:q' , to: 'cases#search' , as: 'search'
  get 'filtered/:q' , to: 'cases#filter' , as: 'filter'
  get 'charity/cases' , to: 'cases#loggedCharity_cases' , as: 'my_cases'
  get 'charity/pending' , to: 'cases#logged_charity_pending_cases' , as: 'charity_pending'

  get 'donor/cases' , to: 'cases#logged_donor_cases' , as: 'donor_cases'
  get 'donor/pending',to: 'cases#logged_donor_pending_cases' , as: 'donor_pending'


  resources :cases do
  end

  devise_for :donors , path: 'donors' ,controllers: {
    sessions: 'donors/sessions'
  }

  devise_for :charities ,path: 'charities', controllers: {
    sessions: 'charities/sessions'
  }

  resources :charities, only: [:index, :show]


  get 'home/index'
  get 'home/:lang', to: 'home#set_locate'
  root 'home#index'

end

app/views/common-partials/_breadcrumbs.html.erb
<!--shortcodes-tabs.html-->
<section class="page-header">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul class="breadcrumb">
          <li><a href="#">Home</a></li>
          <li class="active">Shortcodes</li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <h1>Tabs</h1>
      </div>
    </div>
  </div>
</section>

app/views/common-partials/_footer.html.erb
<footer id="footer">
  <div class="container">
    <div class="row">
      <div class="footer-ribbon">
        <span><%= t 'layout.get_in_touch' %></span>
      </div>
      <div class="col-md-4">
        <h4><%= t 'layout.latest_news' %></h4>
        <div id="tweet" class="twitter" data-plugin-tweets data-plugin-options="{'username': '', 'count': 2}">
          <p><%= t 'layout.comming_soon' %></p>
        </div>
      </div>
      <div class="col-md-6">
        <div class="contact-details">
          <h4><%= t 'layout.contact_us' %></h4>
          <ul class="contact">
            <li><p><i class="fa fa-map-marker"></i> <strong><%= t 'address' %>:</strong>  <%= t('layout.alex_address') %>
            </p></li>
            <li><p><i class="fa fa-phone"></i> <strong><%= t('layout.phone') %>:</strong> (123) 456-789</p></li>
            <li><p><i class="fa fa-envelope"></i> <strong><%= t('layout.email') %>:</strong>
              <a href="mailto:mail@example.com">ITIinfo@iti.gov.eg</a></p></li>
          </ul>
        </div>
      </div>
      <div class="col-md-2">
        <h4><%= t('layout.follow_us') %></h4>
        <ul class="social-icons">
          <li class="social-icons-facebook">
            <a href="https://www.facebook.com/Takafol-111866807234641/" target="_blank" title="Facebook"><i class="fa fa-facebook"></i></a></li>
          <li class="social-icons-twitter">
            <a href="http://www.twitter.com/" target="_blank" title="Twitter"><i class="fa fa-twitter"></i></a></li>
          <li class="social-icons-linkedin">
            <a href="http://www.linkedin.com/" target="_blank" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      <div class="row">
        <div class="col-md-1">
          <a href="/" class="logo">
            <img alt="Porto Website Template" class="img-responsive" src="<%= image_path 'porto-img/logo-footer.png' %>"/>
          </a>
        </div>
        <div class="col-md-7">
          <p><%= t('layout.copyrights') %></p>
        </div>
        <div class="col-md-4">
          <nav id="sub-menu">
            <ul>
              <li><a href="/charities"><%= t('charity.charities') %></a></li>
              <li><a href="/cases"><%= t('layout.cases') %></a></li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/common-partials/_header.html.erb
<!-- TODO: if there's a problem with fonts, I ommmiteed a font from this sction-->
<header id="header" class="header-mobile-nav-only header-flex" data-plugin-options="{'stickyEnabled': true, 'stickyEnableOnBoxed': true, 'stickyEnableOnMobile': true, 'stickyStartAt': 52, 'stickySetTop': '-52px', 'stickyChangeLogo': true}">
  <div class="header-body">
    <div class="header-top">
      <div class="container">
        <p>
          <%= t 'layout.get_in_touch' %>
          <span class="ml-xs"><i class="fa fa-phone"></i> (123) 456-789</span><span class="hidden-xs"> |
          <i class="fa fa-language" aria-hidden="true"></i>
          <% if session[:locale] == "ar" %>
          <a href="/home/en">English</a>
            <% else %>
          <a href="/home/ar">عربي</a>
            <% end %>
        </span>
        </p>


        <div class="header-search hidden-xs">
          <%= form_with(url: "/search/:q", method: "get", local: true, id: "searchForm") do %>

            <%# <form id="searchForm" action="page-search-results.html" method="get"> %>
            <div class="input-group">
              <input type="text" class="form-control" name="search" id="search" placeholder="<%= t 'layout.search' %>..." required>

              <span class="input-group-btn">
											<button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
										</span>
            </div>
          <% end %>
        </div>


      </div>
    </div>
    <div class="header-container container mt-sm">
      <div class="header-row">
        <div class="header-column">
          <div class="header-logo">
            <a href="/">
              <img alt="Porto" width="110" height="75" src="<%= image_path 'mylogo.png' %>">
            </a>
          </div>
        </div>
        <div class="header-column">
          <div class="header-row">
            <div class="header-nav header-nav-stripe">
              <button class="btn header-btn-collapse-nav" data-toggle="collapse" data-target=".header-nav-main">
                <i class="fa fa-bars"></i>
              </button>
              <div class="header-nav-main header-nav-main-square header-nav-main-effect-1 header-nav-main-sub-effect-1 collapse">
                <nav>
                  <ul class="nav nav-pills" id="mainNav">
                    <li class="">
                      <a href="/">
                        <%= t 'layout.home' %>
                      </a>
                    </li>
                    <li class="">
                      <%= link_to t('layout.charities'), charities_path %>
                      </a>
                    </li>
                    <li class="">
                      <%= link_to t('layout.cases'), cases_path %>
                      </a>
                    </li>


                    <li class="dropdown">
                      <% if charity_signed_in? %>
                        <a class="dropdown-toggle" href="<%= profile_path %>">
                          <%= t 'layout.welcome' %> - <strong><%= current_charity.name %></strong>
                        </a>
                        <ul class="dropdown-menu">
                          <li><%= link_to t('layout.logout'), destroy_charity_session_path, method: :delete %></li>
                          <li><%= link_to t('layout.manage_account'), edit_charity_registration_path %></li>
                        </ul>
                      <% elsif donor_signed_in? %>
                        <a class="dropdown-toggle" href="<%= profile_path %>">
                          <%= t 'layout.welcome' %> - <strong><%= current_donor.name %></strong>
                        </a>
                        <ul class="dropdown-menu">
                          <li><%= link_to t('layout.logout'), destroy_donor_session_path, method: :delete %></li>
                          <li><%= link_to t('layout.manage_account'), edit_donor_registration_path %></li>
                        </ul>
                      <% else %>
                        <a class="dropdown-toggle" href="#"><%= t 'layout.manage_account' %></a>
                        <ul class="dropdown-menu">
                          <li class="dropdown-submenu">
                            <a href="#"><%= t 'layout.sign_in' %></a>
                            <ul class="dropdown-menu">
                              <li><%= link_to t('layout.sign_in_charity'), new_charity_session_path %></li>
                              <li><%= link_to t('layout.sign_in_donor'), new_donor_session_path %></li>
                            </ul>
                          </li>
                          <li class="dropdown-submenu">
                            <a href="#"><%= t 'layout.sign_up' %></a>
                            <ul class="dropdown-menu">
                              <li><%= link_to t('layout.sign_up_charity'), new_charity_registration_path %></li>
                              <li><%= link_to t('layout.sign_up_donor'), new_donor_registration_path %></li>
                            </ul>
                          </li>
                        </ul>
                      <% end %>
                    </li>
                  </ul>
                </nav>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/common-partials/_login.html.erb
<!--to be used in auth pages-->
<div class="col-md-6">
  <div class="tabs">
    <ul class="nav nav-tabs">
      <li class="active">
        <a href="#popular" data-toggle="tab"><i class="fa fa-star"></i> Login</a>
      </li>
      <li>
        <a href="#recent" data-toggle="tab"> Sign up</a>
      </li>
    </ul>
    <div class="tab-content">
      <div id="popular" class="tab-pane active">
        <p>tab1</p>
      </div>
      <div id="recent" class="tab-pane">
        <p>tab1</p>
      </div>
    </div>
  </div>
</div>