config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  scope '/checkout' do
    post 'create' , to: 'checkout#create' , as: 'checkout_create'
    get 'cancel' , to: 'checkout#cancel' , as: 'checkout_cancel'
    get 'success' , to: 'checkout#success' , as: 'checkout_success'
  end

  get 'freecases' , to: 'cases#freeindex' , as: 'free_cases'
  get 'profile' , to: 'cases#profile', as: 'profile'
  post 'freecases/protect' , to: 'cases#freeprotect' , as: 'protect_case'
  post 'cases/cancel' , :to => 'cases#remove' , as:'donor_cancel'
  post 'cases/protect' , :to => 'cases#protect' , as: 'donor_protect'
  put 'cases/updatestate/:id', to: 'cases#updatestate'
  get 'search/:q' , to: 'cases#search' , as: 'search'
  get 'filtered/:q' , to: 'cases#filter' , as: 'filter'
  get 'charity/cases' , to: 'cases#loggedCharity_cases' , as: 'my_cases'
  get 'charity/pending' , to: 'cases#logged_charity_pending_cases' , as: 'charity_pending'

  get 'donor/cases' , to: 'cases#logged_donor_cases' , as: 'donor_cases'
  get 'donor/pending',to: 'cases#logged_donor_pending_cases' , as: 'donor_pending'


  resources :cases do
  end

  devise_for :donors , path: 'donors' ,controllers: {
    sessions: 'donors/sessions'
  }

  devise_for :charities ,path: 'charities', controllers: {
    sessions: 'charities/sessions'
  }

  resources :charities, only: [:index, :show]


  get 'home/index'
  get 'home/:lang', to: 'home#set_locate'
  root 'home#index'

end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  before_action :set_case, only: [:show, :edit, :update, :destroy  ]
  # skip_before_action :verify_authenticity_token

  before_action :check_if_charity_is_verified, only: [:freeindex, :updatestate, :freeprotect]

  # GET /cases
  # GET /cases.json
  def index
    @cases = Case.where("amount_needed > #{:amount_obtained}" ).verified.page params[:page]
    @governorates = Governorate.all
    @cities = City.all
    # @cases =Case.all.page params[:page]
  end

  #Free Cases Index
  def freeindex
    @charities_cases_set = CharitiesCase.all.map{|c| c.case_id}
    @cases = Case.where.not(id: @charities_cases_set).order(priority: :desc).page params[:page]
    # @cases = Case.all.order(priority: :desc).page params[:page]
  end

  #Profile
  def profile
    @cases = Case.all.page params[:page]
    render 'profile'
  end

  # GET /cases/1
  # GET /cases/1.json
  def show
    c = Case.find(params["id"])
    if c.charities_cases.count > 0 || charity_signed_in?
      @case = c
    else
      redirect_to cases_path, notice: 'Case not found. or you may not have access to it'
    end
  end

  # Add Case to Donor
  def protect
    @case = Case.find(params["id"])
    if @case.donors_cases.where('state in (?)' , ["pending","cancelled","rejected"]).count < 1
      @case.donors << current_donor
    end
    @case.donors_cases.update(state: "pending" )
    redirect_to case_path(@case)
  end

  #Remove Donor's Protection
  def remove
    if current_donor
    id = current_donor.id
    @case = Case.find(params["id"])
    @case.donors_cases.where(donor_id = "#{id}").first.update(state: "cancelled")
    if @case.donors_cases.where(donor_id = "#{id}").first.state == "cancelled"
       @case.charities_cases.last.update(state: "protected")
    end
    end
    redirect_to cases_path

  end



  #Charity's Approval to Donor's Request
  def updatestate
    @id = params["id"].to_i
    @case =Case.find(@id)
    @case.donors_cases.last.update(state: params["case"]["donors_cases"]["state"])
    if @case.donors_cases.last.state =="approved"
      logger.info 'yessssssss i entered the if block'

      @case.charities_cases.last.update(state: "released")
    end
    redirect_to cases_path
    # redirect_to hi
    # render plain("hiiii")

  end

  #Charity protects the case
  def freeprotect
    @case = Case.find(params["id"])
    @case.charities << current_charity
    @case.charities_cases.update(state: "protected" )
    redirect_to :free_cases
  end






  # GET /cases/new
  def new
    @case = Case.new
  end

  # GET /cases/1/edit
  def edit
  end

  # POST /cases
  # POST /cases.json
  def create

    #If a Charity is signed in the case will be assigned to it automatically
    if current_charity
      @case = @current_charity.cases.create(case_params_charity)
      @case.perform_image_validation = false
      respond_to do |format|
        if @case.save
          format.html { redirect_to @case, notice: 'Case was successfully created.' }
          format.json { render :show, status: :created, location: @case }
          @case.charities_cases.first.update(state: "protected")
        else
          format.html { render :new }
          format.json { render json: @case.errors, status: :unprocessable_entity }
        end
      end

    else

      @case = Case.new(case_params)
      @case.perform_image_validation = true

      respond_to do |format|
        if @case.save
          flash[:city_id] = @case.city_id
          format.html { redirect_to new_case_path, notice: 'Your data was received and we will get back to you soon.' }
          format.json { render :show, status: :created, location: @case }
        else
          format.html { render :new }
          format.json { render json: @case.errors, status: :unprocessable_entity }
        end
      end
    end

  end

  # PATCH/PUT /cases/1
  # PATCH/PUT /cases/1.json
  def update
    respond_to do |format|
      if @case.update(case_params)
        format.html { redirect_to @case, notice: 'Case was successfully updated.' }
        format.json { render :show, status: :ok, location: @case }
      else
        format.html { render :edit }
        format.json { render json: @case.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cases/1
  # DELETE /cases/1.json
  def destroy
    @case.destroy
    respond_to do |format|
      format.html { redirect_to cases_url, notice: 'Case was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def loggedCharity_cases
    if current_charity
    id = current_charity.id
    current_charity_set = Charity.find(id).charities_cases.where(state: "protected").map{|i| i.case_id}
    @cases =Case.where(id: current_charity_set).page params[:page]
    end
  end

  def logged_charity_pending_cases
    if current_charity
    id = current_charity.id
    @cases = Case.joins(:donors_cases).joins(:donors).where("donors_cases.state = 'pending'").joins(:charities_cases).joins(:charities).where("charities.id = #{id}").page params[:page]
    end

  end

  def logged_donor_cases
    if current_donor
    id = current_donor.id
    # TODO: fixme: error in selecting, wrong results
    # @cases = Case.all.where(id:(Case.all.where(donor_id:"#{id}", state:"approved")))
    # @cases =Case.all.where() Donor.find(id).donors_cases.where(state: "approved")
    current_donor_set = Donor.find(id).donors_cases.where(state: "approved").map{|i| i.case_id}

    @cases =Case.where(id: current_donor_set).page params[:page]
    end
  end

  def logged_donor_pending_cases
    if donor_signed_in?
      @cases = Case.joins(:donors_cases).joins(:donors)
            .where("donors_cases.state = ? and donors_cases.donor_id = ?", 'pending', current_donor.id).page params[:page]    else
      redirect_to root_path
    end
  end
  #Search Button
  def search
    search = params[:search].present? ? params[:search] : nil
    @governorates = Governorate.all
    @cities = City.all
    @cases =
    if search
      Case.where(job: search).page params[:page]
      end

  end


  #Filter by address
  def filter
    city = params[:city_id].present? ? params[:city_id] : nil

    if city
      @cases = Case.where(city_id: city).page params[:page]
        else
    @cases
    @cases.page params[:page]
    end

  end



  private
  # Use callbacks to share common setup or constraints between actions.
  def set_case
    @case = Case.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def case_params
    params.fetch(:case).permit(:name , :job ,:email , :national_id , :phone , :children_num ,:marital_status , :NID_img, :description, :city_id, :address)
  end

  #Charity's Special Params to add Case
  def case_params_charity
    params.fetch(:case).permit(:name , :email , :job , :national_id , :phone ,:children_num, :marital_status, :description, :priority ,:amount_needed, :city_id, :address)
  end

  def check_if_charity_is_verified
    if charity_signed_in?
      if !current_charity.verified?
        redirect_to root_path, error: 'You are not allowed to access this part of the site'
      end
    end
  end

end

app/helpers/cases_helper.rb
module CasesHelper
end

app/views/cases/edit.html.erb
<h1>Editing Case</h1>

<%= render 'form', case: @case %>

<%= link_to 'Show', @case %> |
<%= link_to 'Back', cases_path %>

app/views/cases/filter.html.erb
<p id="notice"><%= notice %></p>

<section class="call-to-action call-to-action-quaternary mb-xl">
					<div class="container">
						<div class="row">
							<div class="col-md-12">
								<div class="call-to-action-content">
									<h3>We know it is a hard time, but everything is going to be all right.</h3>
									<p>But until it does<strong> we have your back</strong></p>
								</div>
								<div class="call-to-action-btn">
									<%= link_to "Add Case", new_case_path, :class =>"btn btn-lg btn-success"%><span class="arrow-dark hlb hidden-xs hidden-sm hidden-md appear-animation animated rotateInUpLeft appear-animation-visible" data-appear-animation="rotateInUpLeft" style="top: -12px;"></span>
								</div>
							</div>
						</div>
					</div>
				</section>

<div class="container">
<div class="row">
<div class="col-md-6">

<% if !params['city_id'].nil? %>
     <h1> Cases in:<strong> <%= City.find(params['city_id']).name_en %><strong><h1>
      <% end %>

</div>

</div>
</div>

<%
def cutter (x)
     i=0
    counter=x.split.count
    $a=[]
    while i < counter  do
        $y=x.split(' ')[i][0].capitalize
        i +=1
        $a.push($y)
     end
     $a.join(".")
end
%>




<div class="container">
  <div class='row'>
<%= render :partial => "home/case", :collection => @cases, :as => :c %>
  </div>



</div>


<div class="col-md-12" style="text-align: end;">
		<%= link_to "All Cases", cases_path, :class =>"btn btn-lg btn-borders btn-success ml-xl"%>
		</div>
    </div>
    
<div class="row">
<%= paginate @cases %>
</div>
<br>



</div>
</div>

app/views/cases/freeindex.html.erb
<%if charity_signed_in? %>
        <div class="container">

					<div class="row">
						<div class="col-md-3">
							<aside class="sidebar" id="sidebar" data-plugin-sticky data-plugin-options="{'minWidth': 991, 'containerSelector': '.container', 'padding': {'top': 110}}">

								<h4 class="heading-primary"></h4>
								<ul class="nav nav-list mb-xl show-bg-active">
									<li ><a data-hash data-hash-offset="85" href=<%=profile_path%>>Profile</a></li>
									<li>
										<a data-hash data-hash-offset="85" href="">Cases</a>
										<ul>
											<li><a data-hash data-hash-offset="85" href=<%=my_cases_path%>>My Cases</a></li>
											<li class="active"><a data-hash data-hash-offset="85" href=<%=free_cases_path%>>Free Cases</a></li>
										</ul>
									</li>
									<li><a data-hash data-hash-offset="85" href=<%=charity_pending_path%>>Donation Requests</a></li>
								</ul>

							</aside>
						</div>
						<div class="col-md-9">

 <p id="notice"><%= notice %></p>

<h1>Unverified Cases</h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @cases.each do |c| %>
        <% if c.charities_cases.empty? %>
            <tr>
                <td> <%= c.name %></td>
                <td><%= link_to 'Show', c ,:class => "btn btn-quaternary mr-xs mb-sm"%></td>
                         <td><%= button_to 'Protect Case', protect_case_path , method: :post , params: {id: c.id},:class => "btn btn-success mr-xs mb-sm"  %></td>
            </tr>
        <%end%>
    <% end %>
  </tbody>
</table> 

<div class="row">
<%= paginate @cases %>
</div>
							
						</div>

					</div>

				</div>


    <br>
    <div style="text-align: center;">
	    <%= link_to 'Home', cases_path , :class => "btn" %> |
        <%= link_to 'New Case', new_case_path, :class => "btn" %>

     </div>
        <% else %>
        <div class="container">

				<div class="row">
				<div class="alert alert-danger">
				<strong>Oh!</strong> You are not authorized to view this page.<%= link_to "Sign in as charity", new_charity_session_path, :class => "alert-link" %> to view this.
				</div>
				</div>
				</div>
        

<% end %>

app/views/cases/index.html.erb
<section class="call-to-action call-to-action-quaternary mb-xl">
					<div class="container">
						<div class="row">
							<div class="col-md-12">
								<div class="call-to-action-content">
									<h3><%= t('cases.hard_times')%></h3>
									<p><%=t('cases.but')%><strong> <%= t('cases.we')%></strong></p>
								</div>
								<div class="call-to-action-btn">
									<%= link_to t('cases.add')  , new_case_path, :class =>"btn btn-lg btn-success"%><span class="arrow-dark hlb hidden-xs hidden-sm hidden-md appear-animation animated rotateInUpLeft appear-animation-visible" data-appear-animation="rotateInUpLeft" style="top: -12px;"></span>
								</div>
							</div>
						</div>
					</div>
				</section>
<% if !notice.nil? %>
  <p class="alert alert-danger center">
    <%= notice %>
  </p>
<% end %>
<div class="container">
<div class="row">
<div class="col-md-6">

<h1><%= t('cases.cases')%></h1>

</div>
  <div class="col-md-6" style="text-align: end;">

    <%= form_with(url: "filtered/:q", method: "get", local: true) do %>
      <%= label_tag(:q, t('cases.filter')) %>
      <select class="form-control custom-select" id="select_gov"></select>
      <select class="form-control custom-select" id="city_id" name='city_id' style="display: none;"></select>
      <%= javascript_include_tag 'cities_db', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'select_city_logic' %>
      <%= submit_tag( t('cases.filter_tag'), :class => "btn btn-quaternary mr-xs") %>
    <% end %>
  </div>

</div>
</div>

<%
def cutter (x)
     i=0
    counter=x.split.count
    $a=[]
    while i < counter  do
        $y=x.split(' ')[i][0].capitalize
        i +=1
        $a.push($y)
     end
     $a.join(".")
end
%>




<div class="container">
  <div class='row'>
<%= render :partial => "home/case", :collection => @cases, :as => :c %>
  </div>



</div>
<div class="row">
<%= paginate @cases %>
</div>
<br>


</div>
</div>

app/views/cases/loggedCharity_cases.html.erb
			<%if current_charity%>	
        <div class="container">

					<div class="row">
						<div class="col-md-3">
							<aside class="sidebar" id="sidebar" data-plugin-sticky data-plugin-options="{'minWidth': 991, 'containerSelector': '.container', 'padding': {'top': 110}}">

								<h4 class="heading-primary"></h4>
								<ul class="nav nav-list mb-xl show-bg-active">
									<li ><a data-hash data-hash-offset="85" href=<%=profile_path%>>Profile</a></li>
									<li class="active">
										<a data-hash data-hash-offset="85" href="">Cases</a>
										<ul>
											<li><a data-hash data-hash-offset="85" href=<%=my_cases_path%>>My Cases</a></li>
											<li><a data-hash data-hash-offset="85" href=<%=free_cases_path%>>Free Cases</a></li>
										</ul>
									</li>
									<li><a data-hash data-hash-offset="85" href="#third">Donation Requests</a></li>
								</ul>

							</aside>
						</div>
						<div class="col-md-9">

<%= link_to 'New Case', new_case_path, :class => "btn btn-success mr-xs mb-sm" %>
              <p id="notice"><%= notice %></p>

<h2 class="mb-sm" id="first">My Cases</h2>
 

<table class="table table-hover">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   
     
     <% @cases.each do |c| %>
         <tr>
         <td> <%= c.name %></td>
        <td><%= link_to 'Show', c, :class => "btn btn-quaternary mr-xs mb-sm" %> </td>
        <td><%= link_to 'Edit', edit_case_path(c) , :class => "btn btn-quaternary mr-xs mb-sm" %> 
        <td> <%= link_to 'Unverify', c , method: :delete, data: { confirm: 'Are you sure?' } , :class => "btn btn-danger mr-xs mb-sm"%></td>
    </tr>
    <% end %>
    

  </tbody>
</table>


 <div class="row">

<%= paginate @cases %>
</div>

            
        </div>

    </div>

</div>






<%else%>

<h1> You are not authorized to view this page </h1>

<%end%>

app/views/cases/logged_charity_pending_cases.html.erb
			<%if current_charity%>	
        <div class="container">

					<div class="row">
						<div class="col-md-3">
							<aside class="sidebar" id="sidebar" data-plugin-sticky data-plugin-options="{'minWidth': 991, 'containerSelector': '.container', 'padding': {'top': 110}}">

								<h4 class="heading-primary"></h4>
								<ul class="nav nav-list mb-xl show-bg-active">
									<li ><a data-hash data-hash-offset="85" href=<%=profile_path%>>Profile</a></li>
									<li >
										<a data-hash data-hash-offset="85" href="">Cases</a>
										<ul>
											<li><a data-hash data-hash-offset="85" href=<%=my_cases_path%>>My Cases</a></li>
											<li><a data-hash data-hash-offset="85" href=<%=free_cases_path%>>Free Cases</a></li>
										</ul>
									</li>
									<li class="active"><a data-hash data-hash-offset="85" href=<%=charity_pending_path%>>Donation Requests</a></li>
								</ul>

							</aside>
						</div>
						<div class="col-md-9">


<h2 class="mb-sm" id="first">Pending Donation Requests</h2>
 

<table class="table table-hover">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   
     
     <% @cases.each do |c| %>
         <tr>
         <td> <%= c.name %></td>
        <td><%= link_to 'Show', c, :class => "btn btn-quaternary mr-xs mb-sm" %> </td>
        <td><%= link_to 'Edit', edit_case_path(c) , :class => "btn btn-quaternary mr-xs mb-sm" %> 
    </tr>
    <% end %>
    

  </tbody>
</table>


 <div class="row">

<%= paginate @cases %>
</div>

            
        </div>

    </div>

</div>






<%else%>

<h1> You are not authorized to view this page </h1>

<%end%>

app/views/cases/logged_donor_cases.html.erb
<%if current_donor%>
<div class="container">

			<div class="row">
				<div class="col-md-3">
					<aside class="sidebar" id="sidebar" data-plugin-sticky data-plugin-options="{'minWidth': 991, 'containerSelector': '.container', 'padding': {'top': 110}}">

						<h4 class="heading-primary"></h4>
						<ul class="nav nav-list mb-xl show-bg-active">
							<li ><a data-hash data-hash-offset="85" href=<%=profile_path%>>Profile</a></li>
							<li class="active">
								<a data-hash data-hash-offset="85" href=<%=donor_cases_path%>>My Cases</a>

							</li>
							<li ><a data-hash data-hash-offset="85" href=<%=donor_pending_path%>>Donation Requests</a></li>
						</ul>

					</aside>
				</div>
				<div class="col-md-9">

	<div class="col-md-12">



	<div class="feature-box">
								<div class="feature-box-icon">
									<i class="fa fa-user"></i>
								</div>
								<div class="feature-box-info">
										<h2 class="mb-sm" id="first"><%=  current_donor.name ? current_donor.name : "Undefined"  %></h2>
									<div class="divider divider-small">
										<hr>
									</div>
								</div>
							</div>
						</div>


							
<table class="table table-hover">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   
     
    <% @cases.each do |c| %>
    <tr>
        <td> <%= c.name %></td>
        <td><%= link_to 'Show', c , :class => "btn btn-quaternary mr-xs mb-sm" %> </td>
        <td> <%= button_to "Dismiss" , donor_cancel_path , method: :post , params: {id: c.id} ,data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></td>
    </tr>
    <% end %>
    

  </tbody>
</table>
<div class="row">
<%= paginate @cases %>
</div>

					
				</div>

			</div>

		</div>

<%else%>

<div class="container">

	<div class="row">
		<div class="alert alert-danger">
		<strong>Oh!</strong> You are not authorized to view this page.<%= link_to "Sign in as charity", new_charity_session_path, :class => "alert-link" %> or 
                             <%= link_to "Sign in as donor", new_donor_session_path, :class => "alert-link" %> to view this.
		</div>
	</div>
</div>

<%end%>

app/views/cases/logged_donor_pending_cases.html.erb
<%if current_donor%>
<div class="container">

			<div class="row">
				<div class="col-md-3">
					<aside class="sidebar" id="sidebar" data-plugin-sticky data-plugin-options="{'minWidth': 991, 'containerSelector': '.container', 'padding': {'top': 110}}">

						<h4 class="heading-primary"></h4>
						<ul class="nav nav-list mb-xl show-bg-active">
							<li ><a data-hash data-hash-offset="85" href=<%=profile_path%>>Profile</a></li>
							<li >
								<a data-hash data-hash-offset="85" href=<%=donor_cases_path%>>My Cases</a>

							</li>
							<li class="active"><a data-hash data-hash-offset="85" href=<%=donor_pending_path%>>Donation Requests</a></li>
						</ul>

					</aside>
				</div>
				<div class="col-md-9">

	<div class="col-md-12">



	<div class="feature-box">
								<div class="feature-box-icon">
									<i class="fa fa-user"></i>
								</div>
								<div class="feature-box-info">
										<h2 class="mb-sm" id="first"><%=  current_donor.name ? current_donor.name : "Undefined"  %></h2>
									<div class="divider divider-small">
										<hr>
									</div>
								</div>
							</div>
						</div>


							
<table class="table table-hover">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   
     
    <% @cases.each do |c| %>
    <tr>
        <td> <%= c.name %></td>
        <td><%= link_to 'Show', c , :class => "btn btn-quaternary mr-xs mb-sm" %> </td>
        <td><%= button_to 'Cancel request', donor_cancel_path , method: :post , params: {id: c.id} , :class => "btn btn-danger" %></td>
    </tr>
    <% end %>
    

  </tbody>
</table>

 <div class="row">

<%= paginate @cases %>
</div>
					
				</div>

			</div>

		</div>

<%else%>

<div class="container">

	<div class="row">
		<div class="alert alert-danger">
		<strong>Oh!</strong> You are not authorized to view this page.<%= link_to "Sign in as charity", new_charity_session_path, :class => "alert-link" %> or 
                             <%= link_to "Sign in as donor", new_donor_session_path, :class => "alert-link" %> to view this.
		</div>
	</div>
</div>

<%end%>

app/views/cases/new.html.erb
<% content_for :content do %>
  <div class="container">
    <div class='row rounded border-white'>
      <h2 class="heading-dark center">New Case</h2>
      <% if !notice.nil? %>
        <div class="alert alert-success center" role="alert">
          <%= notice %>
          <br>
          <% if !flash[:city_id].nil? %>
          while we are revising your case. you can search for charities in
            <%= link_to City.find(flash['city_id']).name, '/charities?city_id=' + flash['city_id'].to_s %>
          <% end %>
        </div>
      <% end %>
      <%= render 'form', case: @case %>
      <%= link_to 'Back', cases_path %>
    </div>
  </div>
<% end %>

app/views/cases/profile.html.erb
			<%if current_charity%>	
<div class="container">

			<div class="row">
				<div class="col-md-3">
					<aside class="sidebar" id="sidebar" data-plugin-sticky data-plugin-options="{'minWidth': 991, 'containerSelector': '.container', 'padding': {'top': 110}}">

						<h4 class="heading-primary"></h4>
						<ul class="nav nav-list mb-xl show-bg-active">
							<li class="active"><a data-hash data-hash-offset="85" href=<%=profile_path%>>Profile</a></li>
							<li>
								<a data-hash data-hash-offset="85" href="">Cases</a>
								<ul>
									<li><a data-hash data-hash-offset="85" href=<%=my_cases_path%>>My Cases</a></li>
									<li><a data-hash data-hash-offset="85" href=<%=free_cases_path%>>Free Cases</a></li>
								</ul>
							</li>
							<li><a data-hash data-hash-offset="85" href=<%=charity_pending_path%>>Donation Requests</a></li>
						</ul>

					</aside>
				</div>
				<div class="col-md-9">

	<div class="col-md-12">



	<div class="feature-box">
								<div class="feature-box-icon">
									<i class="fa fa-group"></i>
								</div>
								<div class="feature-box-info">
										<h2 class="mb-sm" id="first"><%=  current_charity.name ? current_charity.name : "Undefined"  %></h2>
									<div class="divider divider-small">
										<hr>
									</div>
								</div>
							</div>
						</div>


							<dl>
			<dt>About</dt>
								<dd><%=  current_charity.description ? current_charity.description : "Undefined"  %></dd>
								
								<dt>Phone number</dt>
								<dd><%=  current_charity.phone_number ? current_charity.phone_number : "Undefined"  %></dd>
								<dt>Address</dt>
								<dd><%=  current_charity.address ? current_charity.address : "Undefined"  %></dd>
								
								<dt>Email-Address</dt>
								<dd><%=  current_charity.email ? current_charity.email : "Undefined"  %></dd>
			<%= link_to 'Edit Profile', edit_charity_registration_path ,:class => "btn btn-quaternary mr-xs mb-sm" %>
							</dl>



					
				</div>

			</div>

		</div>

<%elsif current_donor%>
<div class="container">

			<div class="row">
				<div class="col-md-3">
					<aside class="sidebar" id="sidebar" data-plugin-sticky data-plugin-options="{'minWidth': 991, 'containerSelector': '.container', 'padding': {'top': 110}}">

						<h4 class="heading-primary"></h4>
						<ul class="nav nav-list mb-xl show-bg-active">
							<li class="active"><a data-hash data-hash-offset="85" href=<%=profile_path%>>Profile</a></li>
							<li>
								<a data-hash data-hash-offset="85" href=<%=donor_cases_path%>>My Cases</a>
								
								
							</li>
							<li><a data-hash data-hash-offset="85" href=<%=donor_pending_path%>>Donation Requests</a></li>
						</ul>

					</aside>
				</div>
				<div class="col-md-9">

	<div class="col-md-12">



	<div class="feature-box">
								<div class="feature-box-icon">
									<i class="fa fa-user"></i>
								</div>
								<div class="feature-box-info">
										<h2 class="mb-sm" id="first"><%=  current_donor.name ? current_donor.name : "Undefined"  %></h2>
									<div class="divider divider-small">
										<hr>
									</div>
								</div>
							</div>
						</div>


							<dl>
								
								<dt>National Id</dt>
								<dd><%=  current_donor.national_id  ? current_donor.national_id  : "Undefined"  %></dd>
								
								<dt>Email-Address</dt>
								<dd><%=  current_donor.email ? current_donor.email : "Undefined"  %></dd>

								<dt>National </dt>
								<dd><%=  current_donor.address ? current_donor.address : "Undefined"  %></dd>
			<%= link_to 'Edit Profile', edit_charity_registration_path ,:class => "btn btn-quaternary mr-xs mb-sm" %>
							</dl>



					
				</div>

			</div>

		</div>

<%else%>

<div class="container">

	<div class="row">
		<div class="alert alert-danger">
		<strong>Oh!</strong> You are not authorized to view this page.<%= link_to "Sign in as charity", new_charity_session_path, :class => "alert-link" %> or 
                             <%= link_to "Sign in as donor", new_donor_session_path, :class => "alert-link" %> to view this.
		</div>
	</div>
</div>

<%end%>