config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  scope '/checkout' do
    post 'create' , to: 'checkout#create' , as: 'checkout_create'
    get 'cancel' , to: 'checkout#cancel' , as: 'checkout_cancel'
    get 'success' , to: 'checkout#success' , as: 'checkout_success'
  end

  get 'freecases' , to: 'cases#freeindex' , as: 'free_cases'
  get 'profile' , to: 'cases#profile', as: 'profile'
  post 'freecases/protect' , to: 'cases#freeprotect' , as: 'protect_case'
  post 'cases/cancel' , :to => 'cases#remove' , as:'donor_cancel'
  post 'cases/protect' , :to => 'cases#protect' , as: 'donor_protect'
  put 'cases/updatestate/:id', to: 'cases#updatestate'
  get 'search/:q' , to: 'cases#search' , as: 'search'
  get 'filtered/:q' , to: 'cases#filter' , as: 'filter'
  get 'charity/cases' , to: 'cases#loggedCharity_cases' , as: 'my_cases'
  get 'charity/pending' , to: 'cases#logged_charity_pending_cases' , as: 'charity_pending'

  get 'donor/cases' , to: 'cases#logged_donor_cases' , as: 'donor_cases'
  get 'donor/pending',to: 'cases#logged_donor_pending_cases' , as: 'donor_pending'


  resources :cases do
  end

  devise_for :donors , path: 'donors' ,controllers: {
    sessions: 'donors/sessions'
  }

  devise_for :charities ,path: 'charities', controllers: {
    sessions: 'charities/sessions'
  }

  resources :charities, only: [:index, :show]


  get 'home/index'
  get 'home/:lang', to: 'home#set_locate'
  root 'home#index'

end

app/models/charity.rb
class Charity < ApplicationRecord

  scope :verified, -> { where("verified = 1") }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :name , presence: true
         validates :email, email_format: { message: 'Invalid email format' } , confirmation: true
         validates :phone_number, format: { with: /\A[+-]?\d+\z/ , message:  "Phone must only contain Numbers." } , uniqueness: true

  has_many :charities_cases
  has_many :cases, through: :charities_cases
  belongs_to :city
  accepts_nested_attributes_for :cases

end

app/controllers/charities/confirmations_controller.rb
# frozen_string_literal: true

class Charities::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/charities/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Charities::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/charities/passwords_controller.rb
# frozen_string_literal: true

class Charities::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/charities/registrations_controller.rb
# frozen_string_literal: true

class Charities::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/charities/sessions_controller.rb
# frozen_string_literal: true

class Charities::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  def after_sign_in_path_for(charity)
    my_cases_path	
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/charities/unlocks_controller.rb
# frozen_string_literal: true

class Charities::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController

  rescue_from ActiveRecord::RecordNotFound, with: :dude_wheres_my_record

  def index
    city_id = params['city_id']
    @charities = if city_id.nil?
                   Charity.verified.page params[:page]
                 else
                   Charity.verified.where('city_id = ?', params['city_id']).page params[:page]
                 end
  end

  def show
    @charity = Charity.find(params[:id])
    redirect_to(charities_path, notice: 'Charity not found') unless @charity.verified?
  end

  def dude_wheres_my_record
    redirect_to charities_path, notice: 'Charity not found'
  end
end

app/helpers/charities_helper.rb
module CharitiesHelper
end

app/views/charities/_charity.html.erb
<tr>
  <td><%= link_to charity.name, charity_path(charity) %></td>
  <td><%= charity.email %></td>
  <td><%= charity.address %></td>
  <td><%= charity.phone_number %></td>
  <td><%= charity.description.truncate(100) %></td>
</tr>

app/views/charities/index.erb
<% content_for :content do %>
  <%# TODO: add pagination  %>
  <div class="container">
    <h1 class="center heading-dark"><%= t('charity.charities') %></h1>
    <h3 class="heading-middle-border">
      <% if !params['city_id'].nil? %>
        Viewing only charities in: <%= City.find(params['city_id']).name %>
      <% end %>
    </h3>
    <% if !notice.nil? %>
      <p class="alert alert-danger center">
        <%= notice %>
      </p>
    <% end %>
    <div class="row center">
      <form action="" method="get" class="center">
        <div class="form-group">
          <div class="col-md-6 control-label">
            <div class="input-group">
              <span class="input-group-addon">
                <i class="fa fa-street-view"></i>
              </span>
              <select class="form-control" id="select_gov"></select>
              <select class="form-control" id="city_id" name='city_id' style="display: none;"></select>
            </div>
          </div>
          <input type="submit" class="btn btn-success col-md-3" value="<%= t('charities.filter') %>"/>
        </div>
      </form>
      <%= javascript_include_tag 'cities_db', 'data-turbolinks-track': 'reload' %>
      <% if I18n.locale == :en %>
        <%= javascript_include_tag 'select_city_logic' %>
      <% else %>
        <%= javascript_include_tag 'select_city_logic_ar' %>
      <% end %>

    </div>
    <div class="row">

      <table class="table table-bordered <%= I18n.locale == :ar ? 'rtl' : '' %>">
        <thead class="thead-dark">
        <tr>
          <th><%= t 'name' %></th>
          <th><%= t 'email' %></th>
          <th><%= t 'address' %></th>
          <th><%= t 'phone_number' %></th>
          <th><%= t 'description' %></th>
        </tr>
        </thead>
        <tbody>
        <%= render @charities %>
        </tbody>
      </table>

      <div class="row">
<%= paginate @charities %>
</div>
    </div>
  </div>
<% end %>

app/views/charities/show.html.erb
<section class="section section-default section-default-scale-8">
  <div class="container">
    <div class="row">
      <div class="counters counters-text-light">
        <div class="col-md-12 col-sm-12">
          <div class="counter">
            <strong data-to=<%= @charity.charities_cases.where('state in("protected", "released")').count %> data-append="+">1000+</strong>
            <label>Verified Cases with <%= @charity.name %></label>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="container">
  <div class="row">
    <div class="col-md-9">
      <div class="col-md-12">
        <div class="feature-box">
          <div class="feature-box-icon">
            <i class="fa fa-group"></i>
          </div>
          <div class="feature-box-info">
            <h2 class="mb-sm" id="first"><%= @charity.name ? @charity.name : "Undefined" %></h2>
            <div class="divider divider-small">
              <hr>
            </div>
          </div>
        </div>
      </div>

      <dl>
        <dt>About</dt>
        <dd><%= @charity.description ? @charity.description : "Undefined" %></dd>

        <dt>Phone number</dt>
        <dd><%= @charity.phone_number ? @charity.phone_number : "Undefined" %></dd>
        <dt>Address</dt>
        <dd><%= @charity.address ? @charity.address : "Undefined" %></dd>

        <dt>Email-Address</dt>
        <dd><%= @charity.email ? @charity.email : "Undefined" %></dd>
      </dl>
    </div>
  </div>
</div>